config/routes.rb
Rails.application.routes.draw do
  root 'words#index'

  resources :words do
    collection do
      get 'search'
    end

    member do
      post 'create_comment'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :word
end

app/models/word.rb
# app/models/word.rb

class Word < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_one_attached :image  # 画像用のフィールドを追加
  validates :term, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show]

  def index
    @words = if params[:search]
               Word.where('term LIKE ?', "%#{params[:search]}%")
             else
               Word.all
             end
  end

  def search
    @words = if params[:search]
               Word.where('term LIKE ?', "%#{params[:search]}%")
             else
               Word.all
             end

    render :index
  end

  def show
  end

  def new
    @word = Word.new
  end

  def create
    @word = Word.new(word_params)

    if @word.save
      redirect_to @word, notice: '単語が追加されました。'
    else
      render :new
    end
  end

  def edit
    @word = Word.find(params[:id])
  end

  def update
    @word = Word.find(params[:id])

    if @word.update(word_params)
      redirect_to @word, notice: '単語が更新されました。'
    else
      render :edit
    end
  end

  def show
    @word = Word.find(params[:id])
    @comments = @word.comments
    @comment = Comment.new
  end


  def create_comment
    @word = Word.find(params[:id])
    @comment = @word.comments.new(comment_params)

    if @comment.save
      redirect_to word_path(@word), notice: 'コメントが追加されました。'
    else
      @comments = @word.comments
      render :show
    end
  end
  

  private

  def set_word
    @word = Word.find(params[:id])
  end

  # app/controllers/words_controller.rb

private

def word_params
  params.require(:word).permit(:term, :definition, :image)
end

  

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DictionaryApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/words/_form.html.erb
<!-- app/views/words/_form.html.erb -->

<%= form_with(model: @word, local: true) do |form| %>
  <div class="field">
    <%= form.label :term, '単語' %>
    <%= form.text_field :term, class: 'input-field' %>
  </div>

  <div class="field">
    <%= form.label :definition, '定義' %>
    <%= form.text_area :definition, class: 'input-field' %>
  </div>

  <div class="field">
    <%= form.label :image, '画像' %>
    <%= form.file_field :image, class: 'input-field' %>
  </div>

  <div class="actions">
    <%= form.submit '追加する', class: 'submit-button' %>
  </div>
<% end %>

app/views/words/edit.html.erb
<!-- app/views/words/edit.html.erb -->
<h1>単語編集</h1>
<%= render 'form' %>
<%= link_to '一覧に戻る', words_path %>

app/views/words/index.html.erb
<!-- app/views/words/index.html.erb -->

<h1><%= link_to '単語一覧', root_path %></h1>

<%= link_to '新規単語追加', new_word_path %>

<%= form_with(url: words_path, method: :get) do |form| %>
  <%= form.text_field :search %>
  <%= form.submit '検索' %>
<% end %>

<div class="word-list-container">
  <ul class="word-list">
    <% @words.each do |word| %>
      <li><%= link_to word.term, word %></li>
    <% end %>
  </ul>
</div>

app/views/words/new.html.erb
<h1>新規単語追加</h1>
<%= render 'form' %>
<%= link_to '一覧に戻る', words_path %>

app/views/words/show.html.erb
<!-- app/views/words/show.html.erb -->
<!-- app/views/words/show.html.erb -->

<h1><%= @word.term %></h1>
<p><%= @word.definition %></p>
<%= image_tag @word.image if @word.image.attached? %>

<h2>コメント</h2>
<ul>
  <% @comments.each do |comment| %>
    <li><%= comment.content %></li>
  <% end %>
</ul>

<%= form_with(model: [@word, @comment], url: create_comment_word_path(@word), local: true) do |form| %>
  <%= form.label :content, 'コメント' %>
  <%= form.text_area :content %>
  <%= form.submit 'コメント追加' %>
<% end %>

<%= link_to '編集', edit_word_path(@word) %> |
<%= link_to '一覧に戻る', words_path %>